# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:

  - displayName: 'Install Node.js'
    task: NodeTool@0
    inputs:
      versionSpec: '11.x'

  - displayName: 'Install and Test'
    script: |
      yarn
      yarn lint
      yarn test
